# Simple test workflow to verify the build system
name: Test Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to test'
        type: choice
        options:
        - linux-only
        - windows-only
        - macos-only
        default: linux-only

jobs:
  test-build:
    runs-on: ${{ github.event.inputs.platform == 'linux-only' && 'ubuntu-latest' || github.event.inputs.platform == 'macos-only' && 'macos-latest' || 'windows-latest' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Linux Build
      if: github.event.inputs.platform == 'linux-only'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential yasm nasm pkg-config wget
        
        # Test minimal configuration
        wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
        tar -xf ffmpeg-6.1.tar.xz
        cd ffmpeg-6.1
        
        export BUILD_TYPE=release
        export PLATFORM=linux
        export ARCH=x86_64
        chmod +x ../scripts/configure-minimal.sh
        ../scripts/configure-minimal.sh
        
        # Just test configuration, don't build
        echo "Configuration test passed!"
    
    - name: Test macOS Build
      if: github.event.inputs.platform == 'macos-only'
      run: |
        brew install yasm nasm pkg-config
        
        # Test minimal configuration
        wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
        tar -xf ffmpeg-6.1.tar.xz
        cd ffmpeg-6.1
        
        export BUILD_TYPE=release
        export PLATFORM=darwin
        export ARCH=x86_64
        chmod +x ../scripts/configure-minimal.sh
        ../scripts/configure-minimal.sh
        
        echo "Configuration test passed!"
    
    - name: Test Windows Build
      if: github.event.inputs.platform == 'windows-only'
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-crt-git
          mingw-w64-x86_64-headers-git
          mingw-w64-x86_64-winpthreads
          mingw-w64-x86_64-make
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-pkg-config
    
    - name: Test Windows Configuration
      if: github.event.inputs.platform == 'windows-only'
      shell: msys2 {0}
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-6.1.tar.xz
        tar -xf ffmpeg-6.1.tar.xz
        cd ffmpeg-6.1
        
        export BUILD_TYPE=release
        export PLATFORM=mingw32
        export ARCH=x86_64
        chmod +x ../scripts/configure-minimal.sh
        ../scripts/configure-minimal.sh
        
        echo "Configuration test passed!"